# deployment do banco de dados
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre # tem que ser igual a label declarada no pod
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16 # imagem do banco de dados no Docker Hub
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: fakeshop
        - name: POSTGRES_PASSWORD
          value: fakeshop
        - name: POSTGRES_DB
          value: Pg1234
---
# deployment do service do banco de dados
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
---
# deployment da aplicacao
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fakeshop # tem que ser igual a label declarada no pod
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: eajunior85/fake-shop:v2 # imagem no repositorio Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: fakeshop
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: fakeshop
        - name: FLASK_APP
          value: index.py
---
# deployment do service da aplicacao
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
